### ISSUE TITLE
vnet_route_check exits with code 1 when no VNET routes configured

### ISSUE THREAD

**Issue by antonptashnik** [sonic-net/sonic-utilities#2424]
#### Description

vnet_route_check Sonic Monit script checks route entries integrity among APP and ASIC DBs. Per its [origin PR](https://github.com/sonic-net/sonic-utilities/pull/1300) it should exit with non-zero only when unsync entries found, being more specific PR says:
 
> Returns 0 if there is no inconsistancy found and all VNET routes are aligned in all DBs.
Returns -1 if there is incosistancy found and prints differences between DBs in JSON format to standart output.

Script does not follow aforementioned convention when there's a VNET configured with no routes.
## Steps to reproduce the issue
1. Setup a VNET
Put these 2 snippets each into a separate file and then apply with `sudo config load configfile.json`
```
{
    "VXLAN_TUNNEL": {
        "tunnel_v4": {
            "src_ip": "10.1.0.32"
        }
    }
}
```

```
{
    "VNET": {
        "Vnet_v4_in_v4": {
            "vxlan_tunnel": "tunnel_v4",
            "scope": "default",
            "vni": "10000",
            "peer_list": ""
        }
    }
}
```

2. Run vnet_route_check script and verify an exit code
```
/usr/local/bin/vnet_route_check.py
(0, {'results': {}})
echo $?
1
```

#### Describe the results you received
Script exits with non-zero code (code=1) indicating presence of unsync route entries

#### Describe the results you expected
Script exits with zero code. Since there are no routes configured, routes can be treated in sync hence zero code is expected

#### Output of `show version`

```
SONiC Software Version: SONiC.master.156493-dirty-20221004.185538
Distribution: Debian 11.5
Kernel: 5.10.0-12-2-amd64
Build commit: 95f4af340
Build date: Tue Oct  4 19:02:37 UTC 2022
Built by: AzDevOps@sonic-build-workers-0026VW

Platform: x86_64-accton_as9516_32d-r0
HwSKU: newport
```

**Comment by siqbal1986** [comment]
The behavior of the original script has not been changed in recent code changes. 
The description in the original PR is a bit misleading.
The script returns 0 without (0, {'results': {}}) if no vnet is configured.
however if there is a vnet configured but no routes are present in config DB and ASIC DB, the returned value is a tuple of return code and JSON block with an empty result value.
Changing this behavior now would cause breakage in scripts that are dependent on the output of vnet_route_check.

**Comment by antonptashnik** [comment]
> if there is a vnet configured but no routes are present in config DB and ASIC DB, the returned value is a tuple of return code and JSON block with an empty result value

@siqbal1986 the output you described does not match the actual one. Please pay attention to the output below in the case VNET is configured but not routes present:
```
/usr/local/bin/vnet_route_check.py
(0, {'results': {}})
echo $?
1
```
so this is not right...
> the returned value is a tuple of return code and...

Actually the return code and the first tuple value don't match, where actual values in this case are:
`return code = 1`
`first output tuple value = 0`

I think here both should be 0 but the return code is not
