### ISSUE TITLE
Error messages (pfcFrameCounterCheck & mcCounterCheck) seen in syslog with PR #2606 

### ISSUE THREAD

**Issue by saksarav-nokia** [sonic-net/sonic-utilities#2617]
#### Description
 The following error messages are seen with 202205 image after PR #2206 is merged.
Jan 17 17:53:33.730395 ixre-egl-board3 ERR swss1#orchagent: :- pfcFrameCounterCheck: Invalid port oid 0x15d000000000072
" &  " Jan 18 16:48:51.695100 ixre-egl-board4 ERR swss0#orchagent: :- mcCounterCheck: Invalid port oid 0x5d000000000026"

## Steps to reproduce the issue
1. Load the latest 202205 image in voq chassis with system ports in config file.  These errors messages will be logged in syslog periodically.
2.
3.

#### Describe the results you received
Errors messages in syslog file

#### Describe the results you expected
No error messages

#### Output of `show version`

```
(paste your output here)
```

**Comment by saksarav-nokia** [comment]
The reason for this error is that the functions pfcFrameCounterCheck & mcCounterCheck call getPort function with system port oid . Since getPort function returns false since systemport oid is not added to saiOidToAlias map by addSystemPorts function.

**Comment by saksarav-nokia** [comment]
diff --git a/orchagent/portsorch.cpp b/orchagent/portsorch.cpp
index 0bb8ca6..96483d3 100755
--- a/orchagent/portsorch.cpp
+++ b/orchagent/portsorch.cpp
@@ -7648,6 +7648,7 @@ bool PortsOrch::addSystemPorts()
 
             initializeVoqs( port );
             setPort(port.m_alias, port);
+            saiOidToAlias[system_port_oid] = port.m_alias;
             /* Add system port name map to counter table */
             FieldValueTuple tuple(port.m_system_port_info.alias,
                                   sai_serialize_object_id(system_port_oid));

**Comment by saksarav-nokia** [comment]
drivshell>tm ing  q non
tm ing  q non
No content for table:"MAX VOQ OCCUPANCY: Core 0"
No content for table:"MAX VOQ OCCUPANCY: Core 1"
drivshell>
drivshell>

drivshell>tm ing  q non
tm ing  q non
No content for table:"MAX VOQ OCCUPANCY: Core 0"
No content for table:"MAX VOQ OCCUPANCY: Core 1"
drivshell>tm ing  q non
tm ing  q non
No content for table:"MAX VOQ OCCUPANCY: Core 0"
No content for table:"MAX VOQ OCCUPANCY: Core 1"
drivshell>tm ing vs non g=f
tm ing vs non g=f
No content for table:"MAX VSQ F OCCUPANCY: Core 0"
No content for table:"MAX VSQ F OCCUPANCY: Core 1"
drivshell>tm ing vs non g=f
tm ing vs non g=f
No content for table:"MAX VSQ F OCCUPANCY: Core 0"
No content for table:"MAX VSQ F OCCUPANCY: Core 1"
drivshell>tm ing vs non g=f
tm ing vs non g=f
No content for table:"MAX VSQ F OCCUPANCY: Core 0"
No content for table:"MAX VSQ F OCCUPANCY: Core 1"
drivshell>tm ing vs non g=f
tm ing vs non g=f
No content for table:"MAX VSQ F OCCUPANCY: Core 0"
No content for table:"MAX VSQ F OCCUPANCY: Core 1"

**Comment by kenneth-arista** [comment]
https://github.com/sonic-net/sonic-swss/pull/2632 is the PR targeted at 202205

**Comment by rlhui** [comment]
Fix in 202205.
