### ISSUE TITLE
Error message "pfcFrameCounterCheck: Could not retreive PFC frame count on queue" with PR#2606

### ISSUE THREAD

**Issue by saksarav-nokia** [sonic-net/sonic-utilities#2618]
After fixing the issue reported in #2617 , the following error message is seen in the syslog
pfcFrameCounterCheck: Could not retreive PFC frame count on queue 6 port ixre-egl-board4|asic1|Ethernet-IB1
## Steps to reproduce the issue
1. add a fix in addSystemPorts function in orchagent/portsorch.cpp to add the system port oid to saiOidToAlias to fix the issue reported in #2617 
2. You will see pfcFrameCounterCheck: Could not retreive PFC frame count on queue in syslog periodically. 
3.

#### Describe the results you received

Error messages in syslog
#### Describe the results you expected
No error messages

#### Output of `show version`
202205
```
(paste your output here)
```

**Comment by rlhui** [comment]
https://github.com/sonic-net/sonic-swss/pull/2653 should fix this

**Comment by vmittal-msft** [comment]
PR is merged in.
